<meta name="DC.subject" content ="turnpike trust, Turnpike Act, toll gates, Falmouth, Marazion, Penryn, Helston, Cornwall, public highway, common highway, maintenance of highway, 
Chancery hand, palaeography, handwriting, English handwriting, reading old handwriting" />
<meta name="DC.Description" content="An Act of Parliament for amending and widening the road from Falmouth to Marazion, Cornwall, 1760. The Act, which consists of 20 membranes, forms part of a Parliament roll." />
<meta name="Description" content="Palaeography tutorial - transcribing document 10" />
<meta name="keywords" content="turnpike trust, Turnpike Act, toll gates, Falmouth, Marazion, Penryn, Helston, Cornwall, public highway, common highway, maintenance of highway, 
Chancery hand, palaeography, handwriting, English handwriting, reading old handwriting" />
