<meta name="DC.subject" content="public records, government records, state records, royal archives, storage of public records, storage of government records, storage of state records, repository, Westminster Abbey, New Palace Yard, Westminster palace, 
secretary hand, palaeography, handwriting, English handwriting, old handwriting palaeography, transcribing, old handwriting" />
<meta name="DC.Description" content="This document is a letter sent to Lawrence Earl of Rochester, Lord High Treasurer of England, dated 23 October 1686.  This letter raises problems with two of the locations where royal archives were being stored at Westminster." />
<meta name="Description" content="Palaeography tutorial - transcribing document 5" />
<meta name="keywords" content ="public records, government records, state records, royal archives, storage of public records, storage of government records, storage of state records, repository, Westminster Abbey, New Palace Yard, Westminster palace, 
secretary hand, palaeography, handwriting, English handwriting, old handwriting palaeography, transcribing, old handwriting" />
