<meta name="DC.subject" content="Bulmershe, Berkshire, dissolution of the monasteries, Crown lands, sale of Crown lands, survey of Crown lands, valuation of Crown lands, auditors report, particulars of sale, farm survey, 
legal hand, Exchequer, palaeography, handwriting, English handwriting, old handwriting palaeography, transcribing, old handwriting" />
<meta name="DC.Description" content="This document, dated 17 June 1554, forms part of the particulars for the sale of the manor of Bulmershe, near Reading in Berkshire. Particulars for the sale of property which came to the Crown at the Dissolution of the Monasteries were produced by the auditors of the Court of Augmentations of the Kings Revenue, created in 1536." />
<meta name="Description" content="Palaeography tutorial - transcribing document 6" />
<meta name="keywords" content="Bulmershe, Berkshire, dissolution of the monasteries, Crown lands, sale of Crown lands, survey of Crown lands, valuation of Crown lands, auditors report, particulars of sale, farm survey, 
legal hand, Exchequer, palaeography, handwriting, English handwriting, old handwriting palaeography, transcribing, old handwriting" />

