<meta name="DC.subject" content ="manorial survey, rentals, manorial boundaries, Crown lands, Manorbier, Beere, Pennally, Pembrokeshire, 
secretary hand, palaeography, handwriting, English handwriting, old handwriting, palaeography, transcribing" />
<meta name="DC.Description" content=”This document, dated August 1618, forms part of the manorial survey for Manor of Beere and Penally in Pembrokeshire. This document comes from the records of the Office of the Auditors of Land Revenue.  It consists of two pages from the 1618 survey of the manor of Manorbier and Penally in Pembrokeshire." />
<meta name="Description" content="Palaeography tutorial - transcribing document 7" />
<meta name="keywords" content ="manorial survey, rentals, manorial boundaries, Crown lands, Manorbier, Beere, Pennally, Pembrokeshire, 
secretary hand, palaeography, handwriting, English handwriting, old handwriting, palaeography, transcribing" />


