<meta name="DC.title" content="The National Archives - Palaeography" />
<meta name="DC.rights" content="http://www.nationalarchives.gov.uk/legal/copyright.htm" />
<meta name="DC.publisher" content="The National Archives" />
<meta name="DC.creator" content="The National Archives" />
<meta name="DC.language" content="en-GB" />
<meta name="DC.format" scheme="DCTERMS.IMT" content="text/html" />
<meta name="DC.type" scheme="DCTERMS.DCMIType" content="Text" />
<meta name="DCTERMS.created" scheme="DCTERMS.W3CDTF" content="2004-12-29" />
<meta name="DCTERMS.modified" scheme="DCTERMS.W3CDTF" content="2004-12-29" />
<meta name="eGMS.subject.category" scheme="GCL" content="Libraries and archives" />
<meta name="DCTERMS.temporal" content="1507-1797" />
<meta name="DCTERMS.spatial" content="England, Wales, United Kingdom" />
<meta name="robots" content="noindex, follow" />